method: bayes
metric:
  name: Validation_Epoch_Loss
  goal: minimize
parameters:
  espai_emb_dim: 
    values: [20, 50, 100]
  hidden_size:
    values: [20, 50, 128, 256, 512]
  num_layers:
    values: [1, 3, 5, 10, 16, 32, 128]
  heads:
    values: [1,5,15,30]
  optimizer:
    parameters:
      type:
        values: [adam]
      lr:
        distribution: uniform
        min: 0.00005
        max: 0.1
