method: bayes
metric:
  name: epoch_loss
  goal: minimize
parameters:
  hidden_size:
    values: [100,200]
  num_layers:
    values: [10, 16]
  optimizer:
    parameters:
      type:
        values: [adam]
