method: bayes
metric:
  name: Validation_Epoch_Loss
  goal: minimize
parameters:
  espai_emb_dim: 
    values: [100]
  hidden_size:
    values: [1000]
  num_layers:
    values: [1]
  attnFCdim:
    values: [1000]
  heads:
    values: [10]
  optimizer:
    parameters:
      type:
        values: [adam]
      lr:
        distribution: uniform
        min: 0.00005
        max: 0.01
